### ISSUE TITLE
Board manager

### ISSUE THREAD

**Issue by Diana182** [hilfor/FirstChild#3]
Board manager should do the following: 
- [x] Spawn the babies (with the diapers)
- [x] Receive a touch notification (could even be the touch input) and notify the correct baby/bin on touch.

**Comment by hilfor** [comment]
What do your mean by circle images?

**Comment by hilfor** [comment]
The images are noted in #5

**Comment by hilfor** [comment]
Board Manager should do the following: 
- [ ] Spawn the babies (with the diapers
- [ ] Receive a touch notification (could even be the touch input) and notify the correct baby/bin on touch.

**Comment by Diana182** [comment]
Yes yes!
This task needs to be rewritten with relevant tesks

**Comment by danielgel** [comment]
Done. Board manager spawns all the bomb types corretly
